language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make lint
- make test
- make docker_build
- make docker_push
env:
  secure: Uum0xNwPc4MaOANPQVfu68kCsAZmgDKOxfrLQKMhbui9KI0xa7LhRSy/9g7trjjxP42cQ8BaGN6BDtZesM7XKfhKm77pDBalLaQp++DZ/4bubzb33Os/SUlCCieE9//Kadcg+89nXVLmnicCsQ5wF0hK/VM+kyosa+khLvU0Y/PorQUuHwvUSxom41FJ2qa6MrtH1HG5R/eW58CSN9uxp9BBwEYgYNQKceIYjiJKItrJ/pCFOHEVxF3EXVLrh+H75oAC7rieKYnXcPyMytmbZQ6eidGYOxOULs0DauwrH0M1i9vq0sKFQhs0frL/eYkR40T/m00iaBpPJ9qSzVM+k/EJ4NAWPfp4RJW9llOMDF9DCIG1HZ2zQft3Kt9/2kqe74Rg5748LSX87trlKpju29Lr3WME2AJx9DDE0QJDZ68kPJCg9b/2Tmtl9/PqdaFq2SeGPO6mOaiwfg3bkSXdGdOb2HX8ijSijjWyJDuA5fJsNaQXnXO1usgO6N50peymHqMqQvmI/iKz88no3SObMZFAebXin8e8yPPNcf/NZDt0zS5FR5CFe8cCZL2MmsOV/kQYsYRaF6yta83PAOCYng7Iv8lcjC8bUd53R4XmbmgRZ+QtbOeAdm6QJpSZR29WsoGSkGwcSjBjg+woEPq6SbCrEikMZezVFQ4zIobDWFs=
